import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  BOOTLOADER_MAGIC,
  decodeRequest,
  decodeResponse,
  encodeRequest,
  encodeResponse,
  MAX_MESSAGE_LEN,
  PROTOCOL_VERSION_MAJOR,
  PROTOCOL_VERSION_MINOR,
  ProtocolError,
  Reassembler,
  splitFrames,
  type CommandName,
  type Request,
  type Response,
  type ResponsePayload,
  type StatusName,
} from "./host-protocol";

// Golden vectors shared with the Rust codec; generated by
// protocol/glove80-host-protocol/tests/golden.rs.
const vectorsPath = fileURLToPath(
  new URL("../../../protocol/vectors/host-protocol-v1.json", import.meta.url),
);

interface MessageVector {
  name: string;
  kind: "request" | "response";
  requestId: number;
  message: Record<string, unknown>;
  hex: string;
}

interface FrameVector {
  name: string;
  sourceMessage: string;
  chunkSize: number;
  padded: boolean;
  messageHex: string;
  framesHex: string[];
}

interface GoldenDoc {
  protocol: { major: number; minor: number };
  messages: MessageVector[];
  frames: FrameVector[];
}

const golden: GoldenDoc = JSON.parse(readFileSync(vectorsPath, "utf8"));

function unhex(hex: string): Uint8Array {
  expect(hex.length % 2).toBe(0);
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) {
    out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return out;
}

function toHex(bytes: Uint8Array): string {
  return [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
}

/** The vectors carry byte strings as `dataHex`; the runtime API uses
 * Uint8Array. Everything else matches the runtime shape directly. */
function vectorRequest(message: Record<string, unknown>): Request {
  const { dataHex, ...rest } = message as { dataHex?: string } & Record<string, unknown>;
  if (dataHex !== undefined) {
    return { ...rest, data: unhex(dataHex) } as Request;
  }
  return rest as unknown as Request;
}

function vectorResponse(requestId: number, message: Record<string, unknown>): Response {
  const payloadJson = message.payload as { type: string; dataHex?: string } & Record<
    string,
    unknown
  >;
  const { dataHex, ...payloadRest } = payloadJson;
  const payload = (
    dataHex !== undefined ? { ...payloadRest, data: unhex(dataHex) } : payloadRest
  ) as ResponsePayload;
  return {
    requestId,
    command: message.command as CommandName,
    status: message.status as StatusName,
    payload,
  };
}

describe("host protocol golden vectors", () => {
  it("targets the codec's protocol version", () => {
    expect(golden.protocol).toEqual({
      major: PROTOCOL_VERSION_MAJOR,
      minor: PROTOCOL_VERSION_MINOR,
    });
    expect(golden.messages.length).toBeGreaterThan(0);
    expect(golden.frames.length).toBeGreaterThan(0);
  });

  for (const vector of golden.messages) {
    it(`encodes and decodes ${vector.name}`, () => {
      if (vector.kind === "request") {
        const request = vectorRequest(vector.message);
        expect(toHex(encodeRequest(vector.requestId, request))).toBe(vector.hex);
        expect(decodeRequest(unhex(vector.hex))).toEqual({
          requestId: vector.requestId,
          request,
        });
      } else {
        const response = vectorResponse(vector.requestId, vector.message);
        expect(toHex(encodeResponse(response))).toBe(vector.hex);
        expect(decodeResponse(unhex(vector.hex))).toEqual(response);
      }
    });
  }

  for (const vector of golden.frames) {
    it(`splits and reassembles ${vector.name}`, () => {
      const message = unhex(vector.messageHex);
      const frames = splitFrames(message, vector.chunkSize, vector.padded);
      expect(frames.map(toHex)).toEqual(vector.framesHex);

      const reassembler = new Reassembler();
      vector.framesHex.forEach((frameHex, i) => {
        const result = reassembler.push(unhex(frameHex));
        if (i === vector.framesHex.length - 1) {
          expect(result).toEqual(message);
        } else {
          expect(result).toBeNull();
        }
      });
    });
  }
});

describe("host protocol codec", () => {
  it("round-trips every request variant", () => {
    const requests: Request[] = [
      { command: "getCapabilities", clientMajor: 1, clientMinor: 0 },
      { command: "ping", data: Uint8Array.from([1, 2, 3]) },
      { command: "ping", data: new Uint8Array(0) },
      {
        command: "setCells",
        ttlMs: 0xffffffff,
        cells: [
          {
            key: 79,
            effect: { kind: "breathe", r: 1, g: 2, b: 3, periodMs: 65535, phaseMs: 0, dutyPercent: 0 },
          },
        ],
      },
      { command: "unsetCells", keys: [0, 40, 79] },
      { command: "clearOverlay" },
      { command: "readOverlay" },
      { command: "replaceOverlay", ttlMs: 0, cells: [] },
      { command: "getBrightness" },
      { command: "setBrightness", level: 255 },
      { command: "getToggle", id: 9 },
      { command: "setToggle", id: 9, state: true },
      { command: "enterBootloader", magic: BOOTLOADER_MAGIC, target: "central" },
    ];
    for (const request of requests) {
      const bytes = encodeRequest(7, request);
      expect(decodeRequest(bytes)).toEqual({ requestId: 7, request });
    }
  });

  it("rejects malformed messages", () => {
    expect(() => decodeRequest(Uint8Array.from([0x77, 0, 0, 0]))).toThrow(ProtocolError);
    // Trailing garbage after the declared payload.
    expect(() => decodeRequest(Uint8Array.from([0x12, 1, 0, 0, 9]))).toThrow(
      "length field disagrees",
    );
    // Response flag missing.
    expect(() => decodeResponse(Uint8Array.from([0x12, 1, 0, 0, 0]))).toThrow(ProtocolError);
    // Unknown status.
    expect(() => decodeResponse(Uint8Array.from([0x92, 1, 0xee, 0, 0]))).toThrow(
      "unknown status",
    );
    // partialApply on a non-overlay command.
    expect(() => decodeResponse(Uint8Array.from([0xa0, 1, 0x05, 1, 0, 0]))).toThrow(
      "only valid on overlay writes",
    );
  });

  it("rejects mismatched response payloads", () => {
    expect(() =>
      encodeResponse({
        requestId: 1,
        command: "ping",
        status: "ok",
        payload: { type: "brightness", level: 3 },
      }),
    ).toThrow("does not match");
    expect(() =>
      encodeResponse({
        requestId: 1,
        command: "ping",
        status: "busy",
        payload: { type: "echo", data: new Uint8Array(0) },
      }),
    ).toThrow("does not match");
  });
});

describe("host protocol frame layer", () => {
  it("enforces sequencing and restarts on sequence zero", () => {
    const message = Uint8Array.from({ length: 40 }, (_, i) => i);
    const frames = splitFrames(message, 20);
    expect(frames.length).toBe(3);

    const reassembler = new Reassembler();
    expect(reassembler.push(frames[0])).toBeNull();
    expect(() => reassembler.push(frames[2])).toThrow("expected frame sequence 1, got 2");

    // A fresh sequence-0 frame drops the incomplete message.
    expect(reassembler.push(frames[0])).toBeNull();
    const restart = splitFrames(Uint8Array.from([9]), 20);
    expect(reassembler.push(restart[0])).toEqual(Uint8Array.from([9]));
  });

  it("ignores padding via the per-frame length byte", () => {
    const [frame] = splitFrames(Uint8Array.from([5, 6]), 32, true);
    expect(frame.length).toBe(32);
    expect(new Reassembler().push(frame)).toEqual(Uint8Array.from([5, 6]));
  });

  it("rejects bad frames and oversized messages", () => {
    const reassembler = new Reassembler();
    expect(() => reassembler.push(Uint8Array.from([0]))).toThrow(ProtocolError);
    expect(() => reassembler.push(Uint8Array.from([0x80, 0]))).toThrow("zero-length");
    expect(() => reassembler.push(Uint8Array.from([0x80, 5, 1]))).toThrow(
      "shorter than declared",
    );
    expect(() => splitFrames(new Uint8Array(0), 20)).toThrow("empty message");
    expect(() => splitFrames(Uint8Array.from([1]), 2)).toThrow("below minimum");
    expect(() => splitFrames(new Uint8Array(MAX_MESSAGE_LEN), 3)).toThrow("exceeds 128 frames");
  });
});
